pre_bump_hooks = [
    "cargo check",
]

tag_prefix = "v"

[commit_types]
tests = { changelog_title = "Tests" }

[changelog]
path        = "CHANGELOG.md"
template    = "remote"
remote      = "github.com"
owner       = "WalletConnect"
repository  = "cerberus"

authors = [
    { signature = "Paul Stemmet", username = "bazaah" },
    { signature = "Fabiano Frizzo", username = "ffrizzo" }
]
