name: "release"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: "Install Rust toolchain (stable)"
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            profile: minimal
            default: true

        - name: Cache cargo registry
          uses: Swatinem/rust-cache@v2

        - name: "Cocogitto release"
          id: release
          uses: cocogitto/cocogitto-action@v3
          with:
            check: true
            check-latest-tag-only: true
            release: true
            git-user: 'github-actions'
            git-user-email: 'github-actions@github.com'

        - name: "Generate Changelog"
          run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

        - name: "Update Github release notes"
          uses: softprops/action-gh-release@v1
          with:
            body_path: GITHUB_CHANGELOG.md
            tag_name: ${{ steps.release.outputs.version }}
            token: ${{ secrets.GITHUB_TOKEN }}
